Repository joanafbrito/tomates-podres, pull requests merged in 2021-08, with the labels that each got.

#9 Feature/single api fetch
  src/App.js
  src/ChosenOne.css
  src/ChosenOne.js
  src/apiCalls.js
Labels: bug, enhancement, Iteration 2, Iteration 3

#11 Feacture/video
  README.md
  package.json
  src/App.js
  src/ChosenOne.js
  src/apiCalls.js
Labels: enhancement, Iteration 3

#13 Feature/create navbar
  src/App.css
  src/App.js
  src/ChosenOne.css
  src/MovieCard.css
  src/Movies.css
  src/Navbar.css
  src/Navbar.js
  src/index.css
Labels: enhancement, Iteration 2, Iteration 3

#16 Feature/css
  src/App.css
  src/ChosenOne.css
  src/MovieCard.css
  src/Movies.css
  src/Movies.js
  src/Navbar.css
  src/Navbar.js
  src/images/magGlass.svg
  src/images/magGlass2.png
  src/images/tomato.svg
  src/images/tomato1.svg
  src/index.css
Labels: enhancement, HTML, CSS

#19 Feature/star rating
  package-lock.json
  package.json
  src/ChosenOne.css
  src/ChosenOne.js
  src/Movies.js
  src/RatingStar.css
  src/RatingStar.js
Labels: enhancement, CSS

#18 Feature/make search bar
  src/App.js
  src/Navbar.css
  src/Navbar.js
  src/SearchBar.js
Labels: enhancement

#21 Organize components
  src/ChosenOne.css
  src/ChosenOne.js
  src/components/App.css
  src/components/App.js
  src/components/ChosenOne.css
  src/components/ChosenOne.js
  src/components/MovieCard.css
  src/components/MovieCard.js
  src/components/Movies.css
  src/components/Movies.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/components/RatingStar.css
  src/components/RatingStar.js
  src/components/SearchBar.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
Labels: CSS, Refactor
