Repository joanafbrito/tomates-podres, pull requests merged in 2021-09, with the labels that each got.

#23 Feature/add react router
  package-lock.json
  package.json
  src/components/App.js
  src/components/ChosenOne.css
  src/components/ChosenOne.js
  src/components/MovieCard.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/components/RatingStar.js
  src/index.js
Labels: enhancement, Iteration 4, Refactor

#25 Feature/choosen one info and slyting
  src/components/App.js
  src/components/MovieCard.css
  src/components/Movies.css
  src/components/Navbar.css
  src/components/Navbar.js
Labels: CSS

#26 Feature/cypress
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/home_page_spec.js
  cypress/integration/movie_info_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/components/App.css
  src/components/App.js
  src/components/ChosenOne.css
  src/components/MovieCard.css
  src/components/Movies.css
  src/components/Navbar.css
  src/components/SearchBar.js
Labels: enhancement, CypressTest

#33 Refactor/bug fixes
  package-lock.json
  src/components/App.js
  src/components/ChosenOne.js
  src/components/ErrorInformation.js
  src/components/MovieCard.css
  src/components/MovieCard.js
  src/components/Movies.js
  src/components/Navbar.js
Labels: bug

#34 Feature/css polishing
  src/components/App.css
  src/components/App.js
  src/components/ChosenOne.css
  src/components/ChosenOne.js
  src/components/ErrorInformation.css
  src/components/ErrorInformation.js
  src/components/MovieCard.css
  src/components/Movies.css
  src/components/Movies.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/components/RatingStar.css
  src/components/RatingStar.js
Labels: bug, CSS

#36 Refactor/code clean
  .github/pull_request_template.md
  cypress/support/commands.js
  src/components/App.js
  src/components/ChosenOne.js
  src/components/ErrorInformation.css
  src/components/Movies.js
Labels: CSS, Refactor

#38 Refactor/improve accessibility
  src/components/MovieCard.js
  src/components/Navbar.css
  src/components/Navbar.js
Labels: Refactor

#39 Feature/add eslint
  package-lock.json
  package.json
  src/components/App.js
  src/components/ChosenOne.js
  src/components/MovieCard.js
  src/components/Movies.js
  src/components/Navbar.js
Labels: Refactor

#41 Refactor routes for right deploy link
  cypress/support/commands.js
  package.json
  src/components/App.js
  src/components/MovieCard.js
  src/components/Navbar.js
Labels: enhancement, Refactor
